"""initial B schema

Revision ID: 82c244f0e023
Revises: 
Create Date: 2025-08-30 14:41:02.096428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82c244f0e023'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_number', sa.String(length=32), nullable=False))
        batch_op.create_index(batch_op.f('ix_users_employee_number'), ['employee_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_employee_number'))
        batch_op.drop_column('employee_number')

    # ### end Alembic commands ###
